
const DEFAULT_KEG_SIZE_ML = 20000;
const HEARTBEAT_TIMEOUT_MS = 30000;
const DB_POLL_INTERVAL_MS = 5000;
const HEARTBEAT_CHECK_INTERVAL_MS = 10000;
const PORT = 3001;

module.exports = {
  DEFAULT_KEG_SIZE_ML,
  HEARTBEAT_TIMEOUT_MS,
  DB_POLL_INTERVAL_MS,
  HEARTBEAT_CHECK_INTERVAL_MS,
  PORT,
};
